#!/bin/sh

# Husky
huskyPackage='husky'
if [ `npm list | grep -c $huskyPackage` -eq 0 ]; then
  npm install $huskyPackage --no-shrinkwrap
fi

# Commit lint CLI
commitlintCliPackage='@commitlint/cli'
if [ `npm list | grep -c $commitlintCliPackage` -eq 0 ]; then
  npm install $commitlintCliPackage --no-shrinkwrap
fi

# Commit lint config conventional
commitlintConfig='@commitlint/config-conventional'
if [ `npm list | grep -c $commitlintConfig` -eq 0 ]; then
  npm install $commitlintConfig --no-shrinkwrap
fi

scriptPath="node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  if [ "${HUSKY_DEBUG}" = "true" ] || [ "${HUSKY_DEBUG}" = "1" ]; then
    echo "husky:debug $1"
  fi
}

debug "husky v3.1.0 (created at 12/20/2019, 09:44:41)"
debug "$hookName hook started"
debug "Current working directory is '`pwd`'"

if [ "${HUSKY_SKIP_HOOKS}" = "true" ] || [ "${HUSKY_SKIP_HOOKS}" = "1" ]; then
  debug "HUSKY_SKIP_HOOKS is set to ${HUSKY_SKIP_HOOKS}, skipping hook"
  exit 0
fi

if [ "${HUSKY_USE_YARN}" = "true" ] || [ "${HUSKY_USE_YARN}" = "1" ]; then
  debug "Calling husky through Yarn"
  yarn husky-run $hookName "$gitParams"
else

  if [ -f "$scriptPath" ]; then
    # if [ -t 1 ]; then
    #   exec < /dev/tty
    # fi
    if [ -f ~/.huskyrc ]; then
      debug "Sourcing '~/.huskyrc'"
      . ~/.huskyrc
    fi
    node "$scriptPath" $hookName "$gitParams"
  else
    echo "Can't find Husky, skipping $hookName hook"
    echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
  fi
fi